; PlatformIO Project Configuration File
;default_envs = rpu_os_hardware_rev3_rx

[common]
; Common build flags for all environments
build_flags =
    -DRPU_OS_USE_DIP_SWITCHES
    -DRPU_MPU_BUILD_FOR_6800=1
    -DRPU_OS_USE_WAV_TRIGGER=1
;    -DWAVTRIGGER_LACKS_RX=1
;    -DRPU_OS_USE_SB100

;; Hardware Rev 2
;[env:rpu_os_hardware_rev2]
;extends = common
;platform = atmelavr
;board = nanoatmega328
;framework = arduino
;build_flags =
;    ${common.build_flags}
;    -DRPU_OS_HARDWARE_REV=2
;    -DWAVTRIGGER_LACKS_RX=1

; Hardware Rev 3 - MEGA 2560 Pro (original)
[env:rpu_os_hardware_rev3]
extends = common
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    ${common.build_flags}
    -DRPU_OS_HARDWARE_REV=3
    -DWAVTRIGGER_LACKS_RX=1

; Hardware Rev 3 - MEGA 2560 Pro (RX line added to WAV Trigger)
[env:rpu_os_hardware_rev3_rx]
extends = common
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    ${common.build_flags}
    -DRPU_OS_HARDWARE_REV=3


; Hardware Rev 4 - MEGA 2560 Pro with display & WIFI
[env:rpu_os_hardware_rev4]
extends = common
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    ${common.build_flags}
    -DRPU_OS_HARDWARE_REV=4

; Hardware Rev 100 - Second RPU with display and WIFI socket
[env:rpu_os_hardware_rev100]
extends = common
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    ${common.build_flags}
    -DRPU_OS_HARDWARE_REV=100

; Hardware Rev 101 - Second RPU with display and WIFI socket
[env:rpu_os_hardware_rev101]
extends = common
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    ${common.build_flags}
    -DRPU_OS_HARDWARE_REV=101

; Hardware Rev 102 - Second RPU with display and WIFI socket
[env:rpu_os_hardware_rev102]
extends = common
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    ${common.build_flags}
    -DRPU_OS_HARDWARE_REV=102

; Stub to test dash32
[env:dash32]
extends = common
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    ${common.build_flags}
    -DRPU_OS_USE_DASH32
    -DRPU_OS_HARDWARE_REV=3

; Stub to test dash51
[env:dash51]
extends = common
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    ${common.build_flags}
    -DRPU_OS_USE_DASH51
    -DRPU_OS_HARDWARE_REV=3

; Stub to test sb100
[env:sb100]
extends = common
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    ${common.build_flags}
    -DRPU_OS_USE_SB100
    -DRPU_OS_HARDWARE_REV=3

; Stub to test sb300
[env:sb300]
extends = common
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags =
    ${common.build_flags}
    -DRPU_OS_USE_SB300
    -DRPU_OS_HARDWARE_REV=3
