
#include "RPU_config.h"
#include "RPU.h"

#if RPU_OS_HARDWARE_REV_IS(100)

#if !defined(__AVR_ATmega2560__)
#error "RPU_OS_HARDWARE_REV 100 requires ATMega2560, check RPU_Config.h and adjust settings"
#endif

#include "RPU_Internal.h"
#include <Arduino.h>

// Rev 100 pin map (MEGA 2560 in CPU socket):
//   D2=BUFFER_DISABLE  D3=PHI2  D4=VMA  D5=R/W  D6-D12=D0-D6  D13=SWITCH
//   D14=HALT/RESET  D15=D7  D16-D31=A0-A15
// Clock is generated by the Arduino (not read from MPU).

static constexpr uint8_t RPU_VMA_PIN = 4;
static constexpr uint8_t RPU_RW_PIN = 5;
static constexpr uint8_t RPU_PHI2_PIN = 3;
static constexpr uint8_t RPU_SWITCH_PIN = 13;
static constexpr uint8_t RPU_BUFFER_DISABLE = 2;
static constexpr uint8_t RPU_HALT_PIN = 14;
static constexpr uint8_t RPU_RESET_PIN = 14;

void RPU_DataWrite(int address, uint8_t data) {
   DDRH = DDRH | 0x78;
   DDRB = DDRB | 0x70;
   DDRJ = DDRJ | 0x01;

   PORTE = (PORTE & 0xF7); // R/W LOW

   PORTH = (PORTH & 0x87) | ((data & 0x0F) << 3); // data bits 0-3 on H3-H6
   PORTB = (PORTB & 0x8F) | ((data & 0x70));       // data bits 4-6 on B4-B6
   PORTJ = (PORTJ & 0xFE) | (data >> 7);           // data bit 7 on J0

   PORTH = (PORTH & 0xFC) | ((address & 0x0001) << 1) | ((address & 0x0002) >> 1); // A0-A1
   PORTD = (PORTD & 0xF0) | ((address & 0x0004) << 1) | ((address & 0x0008) >> 1) |
           ((address & 0x0010) >> 3) | ((address & 0x0020) >> 5); // A2-A5
   PORTA = ((address & 0x3FC0) >> 6);                             // A6-A13
   PORTC = (PORTC & 0x3F) | ((address & 0x4000) >> 7) | ((address & 0x8000) >> 9); // A14-A15

   PORTE &= ~0x20; // clock low
   PORTG = PORTG | 0x20; // VMA ON
   PORTE |= 0x20;  // clock high
   PORTE &= ~0x20; // clock low
   PORTE |= 0x20;  // clock high
   PORTG = PORTG & 0xDF; // VMA OFF

   PORTH = (PORTH & 0xFC);
   PORTD = (PORTD & 0xF0);
   PORTA = 0;
   PORTC = (PORTC & 0x3F);

   PORTE = (PORTE | 0x08); // R/W HIGH

   DDRH = DDRH & 0x87;
   DDRB = DDRB & 0x8F;
   DDRJ = DDRJ & 0xFE;
}

uint8_t RPU_DataRead(int address) {
   DDRH = DDRH & 0x87;
   DDRB = DDRB & 0x8F;
   DDRJ = DDRJ & 0xFE;

   DDRE = DDRE | 0x08;
   PORTE = (PORTE | 0x08); // R/W HIGH

   PORTH = (PORTH & 0xFC) | ((address & 0x0001) << 1) | ((address & 0x0002) >> 1); // A0-A1
   PORTD = (PORTD & 0xF0) | ((address & 0x0004) << 1) | ((address & 0x0008) >> 1) |
           ((address & 0x0010) >> 3) | ((address & 0x0020) >> 5); // A2-A5
   PORTA = ((address & 0x3FC0) >> 6);                             // A6-A13
   PORTC = (PORTC & 0x3F) | ((address & 0x4000) >> 7) | ((address & 0x8000) >> 9); // A14-A15

   PORTE &= ~0x20; // clock low
   PORTG = PORTG | 0x20; // VMA ON
   PORTE |= 0x20;  // clock high
   PORTE &= ~0x20; // clock low
   PORTE |= 0x20;  // clock high

   uint8_t inputData;
   inputData = (PINH & 0x78) >> 3;
   inputData |= (PINB & 0x70);
   inputData |= PINJ << 7;

   PORTG = PORTG & 0xDF; // VMA OFF
   PORTE = (PORTE & 0xF7); // R/W LOW

   PORTH = (PORTH & 0xFC);
   PORTD = (PORTD & 0xF0);
   PORTA = 0;
   PORTC = (PORTC & 0x3F);

   return inputData;
}

void RPU_HW_SetupPorts(uint16_t &) {
   // Rev 100 has no additional port setup after early init
}

uint16_t RPU_InitializeBSP(uint16_t, uint8_t) {
   // Rev 100 boots directly to Arduino code with no original-MPU option
   return 0;
}

#endif // RPU_OS_HARDWARE_REV 100
