#ifndef SOUND_EFFECTS_H
#define SOUND_EFFECTS_H

#include <stdint.h>

/*********************************************************************
    Sound Effect Definitions
*********************************************************************/
constexpr uint8_t SOUND_EFFECT_NONE = 0;
constexpr uint8_t SOUND_EFFECT_DT_SKILL_SHOT = 1;
constexpr uint8_t SOUND_EFFECT_ROLLOVER_SKILL_SHOT = 2;
constexpr uint8_t SOUND_EFFECT_SU_SKILL_SHOT = 3;
constexpr uint8_t SOUND_EFFECT_LEFT_SPINNER = 4;
constexpr uint8_t SOUND_EFFECT_RIGHT_SPINNER = 5;
constexpr uint8_t SOUND_EFFECT_ROLLOVER = 6;
constexpr uint8_t SOUND_EFFECT_LEFT_INLANE = 7;
constexpr uint8_t SOUND_EFFECT_RIGHT_INLANE = 8;
constexpr uint8_t SOUND_EFFECT_RIGHT_OUTLANE = 9;
constexpr uint8_t SOUND_EFFECT_TOP_BUMPER_HIT = 10;
constexpr uint8_t SOUND_EFFECT_BOTTOM_BUMPER_HIT = 11;
constexpr uint8_t SOUND_EFFECT_DROP_TARGET = 12;
constexpr uint8_t SOUND_EFFECT_ADD_CREDIT = 13;
constexpr uint8_t SOUND_EFFECT_RESCUE_FROM_THE_DEEP = 14;
constexpr uint8_t SOUND_EFFECT_SHOOT_AGAIN = 15;
constexpr uint8_t SOUND_EFFECT_FEEDING_FRENZY = 16;
constexpr uint8_t SOUND_EFFECT_FEEDING_FRENZY_START = 17;
constexpr uint8_t SOUND_EFFECT_SHARP_SHOOTER_START = 18;
constexpr uint8_t SOUND_EFFECT_JACKPOT = 19;
constexpr uint8_t SOUND_EFFECT_ADD_PLAYER_1 = 20;
constexpr uint8_t SOUND_EFFECT_ADD_PLAYER_2 = SOUND_EFFECT_ADD_PLAYER_1 + 1;
constexpr uint8_t SOUND_EFFECT_ADD_PLAYER_3 = SOUND_EFFECT_ADD_PLAYER_1 + 2;
constexpr uint8_t SOUND_EFFECT_ADD_PLAYER_4 = SOUND_EFFECT_ADD_PLAYER_1 + 3;
constexpr uint8_t SOUND_EFFECT_PLAYER_1_UP = 24;
constexpr uint8_t SOUND_EFFECT_PLAYER_2_UP = SOUND_EFFECT_PLAYER_1_UP + 1;
constexpr uint8_t SOUND_EFFECT_PLAYER_3_UP = SOUND_EFFECT_PLAYER_1_UP + 2;
constexpr uint8_t SOUND_EFFECT_PLAYER_4_UP = SOUND_EFFECT_PLAYER_1_UP + 3;
constexpr uint8_t SOUND_EFFECT_BALL_OVER = 30;
constexpr uint8_t SOUND_EFFECT_GAME_OVER = 31;
constexpr uint8_t SOUND_EFFECT_BONUS_COUNT = 32;
constexpr uint8_t SOUND_EFFECT_2X_BONUS_COUNT = 33;
constexpr uint8_t SOUND_EFFECT_3X_BONUS_COUNT = 34;
constexpr uint8_t SOUND_EFFECT_4X_BONUS_COUNT = 35;
constexpr uint8_t SOUND_EFFECT_5X_BONUS_COUNT = 36;
constexpr uint8_t SOUND_EFFECT_EXTRA_BALL = 37;
constexpr uint8_t SOUND_EFFECT_TILT_WARNING = 39;
constexpr uint8_t SOUND_EFFECT_MATCH_SPIN = 40;
constexpr uint8_t SOUND_EFFECT_LOWER_SLING = 41;
constexpr uint8_t SOUND_EFFECT_UPPER_SLING = 42;
constexpr uint8_t SOUND_EFFECT_10PT_SWITCH = 43;
constexpr uint8_t SOUND_EFFECT_SAUCER_HIT_5K = 44;
constexpr uint8_t SOUND_EFFECT_SAUCER_HIT_10K = 45;
constexpr uint8_t SOUND_EFFECT_SAUCER_HIT_20K = 46;
constexpr uint8_t SOUND_EFFECT_SAUCER_HIT_30K = 47;
constexpr uint8_t SOUND_EFFECT_SHARP_SHOOTER_HIT = 48;
constexpr uint8_t SOUND_EFFECT_DROP_TARGET_CLEAR_1 = 50;
constexpr uint8_t SOUND_EFFECT_DROP_TARGET_CLEAR_2 = SOUND_EFFECT_DROP_TARGET_CLEAR_1 + 1;
constexpr uint8_t SOUND_EFFECT_DROP_TARGET_CLEAR_3 = SOUND_EFFECT_DROP_TARGET_CLEAR_1 + 2;
constexpr uint8_t SOUND_EFFECT_DROP_TARGET_CLEAR_4 = SOUND_EFFECT_DROP_TARGET_CLEAR_1 + 3;
constexpr uint8_t SOUND_EFFECT_DROP_TARGET_CLEAR_5 = SOUND_EFFECT_DROP_TARGET_CLEAR_1 + 4;
constexpr uint8_t SOUND_EFFECT_FIRST_SU_SWITCH_HIT = 55;
constexpr uint8_t SOUND_EFFECT_SECOND_SU_SWITCH_HIT = SOUND_EFFECT_FIRST_SU_SWITCH_HIT + 1;
constexpr uint8_t SOUND_EFFECT_THIRD_SU_SWITCH_HIT = SOUND_EFFECT_FIRST_SU_SWITCH_HIT + 2;
constexpr uint8_t SOUND_EFFECT_FOURTH_SU_SWITCH_HIT = SOUND_EFFECT_FIRST_SU_SWITCH_HIT + 3;
constexpr uint8_t SOUND_EFFECT_FIFTH_SU_SWITCH_HIT = SOUND_EFFECT_FIRST_SU_SWITCH_HIT + 4;
constexpr uint8_t SOUND_EFFECT_EXPLORE_QUALIFIED = 60;
constexpr uint8_t SOUND_EFFECT_STANDUPS_CLEARED = 61;
constexpr uint8_t SOUND_EFFECT_EXPLORE_HIT = 62;
constexpr uint8_t SOUND_EFFECT_EXPLORE_THE_DEPTHS_START = 63;
constexpr uint8_t SOUND_EFFECT_SHARP_SHOOTER_QUALIFIED = 65;
constexpr uint8_t SOUND_EFFECT_FEEDING_FRENZY_QUALIFIED = 66;
constexpr uint8_t SOUND_EFFECT_MODE_FINISHED = 67;
constexpr uint8_t SOUND_EFFECT_SS_AND_FF_START = 68;
constexpr uint8_t SOUND_EFFECT_SS_AND_ETD_START = 69;
constexpr uint8_t SOUND_EFFECT_FF_AND_ETD_START = 70;
constexpr uint8_t SOUND_EFFECT_MEGA_STACK_START = 71;
constexpr uint8_t SOUND_EFFECT_SWIM_AGAIN = 72;
constexpr uint8_t SOUND_EFFECT_DEEP_BLUE_SEA_MODE = 73;
constexpr uint8_t SOUND_EFFECT_TRIDENT_INTRO = 89;
constexpr uint8_t SOUND_EFFECT_BACKGROUND_1 = 90;
constexpr uint8_t SOUND_EFFECT_BACKGROUND_2 = 91;
constexpr uint8_t SOUND_EFFECT_BACKGROUND_3 = 92;
constexpr uint8_t SOUND_EFFECT_BACKGROUND_4 = 93;
constexpr uint8_t SOUND_EFFECT_BACKGROUND_5 = 94;
constexpr uint8_t SOUND_EFFECT_BACKGROUND_6 = 95;
constexpr uint8_t SOUND_EFFECT_BACKGROUND_WIZ = 96;
constexpr uint8_t SOUND_EFFECT_BACKGROUND_FOR_SINGLE_MODE = 97;
constexpr uint8_t SOUND_EFFECT_BACKGROUND_FOR_DOUBLE_MODE = 98;
constexpr uint8_t SOUND_EFFECT_BACKGROUND_FOR_TRIPLE_MODE = 99;
constexpr uint8_t SOUND_EFFECT_COIN_DROP_1 = 100;
constexpr uint8_t SOUND_EFFECT_COIN_DROP_2 = 101;
constexpr uint8_t SOUND_EFFECT_COIN_DROP_3 = 102;

constexpr uint8_t SOUND_EFFECT_SELF_TEST_CPC_START = 180;
constexpr uint8_t SOUND_EFFECT_SELF_TEST_AUDIO_OPTIONS_START = 190;

constexpr uint16_t SOUND_EFFECT_DIAG_START = 1900;
constexpr uint16_t SOUND_EFFECT_DIAG_CREDIT_RESET_BUTTON = 1900;
constexpr uint16_t SOUND_EFFECT_DIAG_SELECTOR_SWITCH_ON = 1901;
constexpr uint16_t SOUND_EFFECT_DIAG_SELECTOR_SWITCH_OFF = 1902;
constexpr uint16_t SOUND_EFFECT_DIAG_STARTING_ORIGINAL_CODE = 1903;
constexpr uint16_t SOUND_EFFECT_DIAG_STARTING_NEW_CODE = 1904;
constexpr uint16_t SOUND_EFFECT_DIAG_ORIGINAL_CPU_DETECTED = 1905;
constexpr uint16_t SOUND_EFFECT_DIAG_ORIGINAL_CPU_RUNNING = 1906;
constexpr uint16_t SOUND_EFFECT_DIAG_PROBLEM_PIA_U10 = 1907;
constexpr uint16_t SOUND_EFFECT_DIAG_PROBLEM_PIA_U11 = 1908;
constexpr uint16_t SOUND_EFFECT_DIAG_PROBLEM_PIA_1 = 1909;
constexpr uint16_t SOUND_EFFECT_DIAG_PROBLEM_PIA_2 = 1910;
constexpr uint16_t SOUND_EFFECT_DIAG_PROBLEM_PIA_3 = 1911;
constexpr uint16_t SOUND_EFFECT_DIAG_PROBLEM_PIA_4 = 1912;
constexpr uint16_t SOUND_EFFECT_DIAG_PROBLEM_PIA_5 = 1913;
constexpr uint16_t SOUND_EFFECT_DIAG_STARTING_DIAGNOSTICS_MODE = 1914;

#endif // SOUND_EFFECTS_H
